from typing import Protocol, List, Dict, Any

class LLMProvider(Protocol):
    def grade_exercise(self, question: str, standard_answer: str, user_answer: str, user_level: str | None) -> Dict[str, Any]: ...
    def tutor_reply(self, scenario: str, message: str, state: Dict[str, Any]) -> Dict[str, Any]: ...
    def tutor_report(self, session_id: str, transcript: List[Dict[str, str]]) -> Dict[str, Any]: ...
